---
- name: Install dependencies
  ansible.builtin.include_tasks: install_dependencies.yml
  when: ansible_os_family == "Debian"

- name: Add HashiCorp repository
  ansible.builtin.include_tasks: add_hashicorp_repository.yml
  when: ansible_os_family == "Debian"

- name: Install Packer
  ansible.builtin.package:
    name: packer
    state: present
  when: ansible_os_family == "Debian"
